### ISSUE TITLE
.getCnpjCpf() retorna dados diferentes entre as versões

### ISSUE THREAD

**Issue by phillipig** [Samuel-Oliveira/Java_Certificado#18]
Olá Samuel, boa tarde!

Não sei se é exatamente um bug, mas acabou me afetando em produção, e precisei reverter para a versão antiga da lib, e resolvi trazer para a discussão.

Tenho seguinte certificado:
![image](https://github.com/Samuel-Oliveira/Java_Certificado/assets/5054717/557dd756-2127-43e1-b059-338d9b0e744f)

- Na versão 2.14, se eu chamo o método .getCnpjCpf() depois de carregar esse certificado via certificadoPfxBytes, eu tenho o CNPJ: 454XXXXXXXX138

- Na versão 3.1 se eu chamo esse mesmo método .getCnpjCpf(), para o mesmo certificado, vem o CPF: 426XXXXX874.

Parece que ele pegou o primeiro elemento da string no rejex do (cert.getSubjectX500Principal().getName()) no método getDocumentoFromCertificado, mas o que eu precisava mesmo, era validar o CNPJ.

Nos casos de certificados que possui esses dois dados, talvez obedecer a precedencia do nome do seu método funcionaria para mim (retornar o CNPJ primeiro se existir), ou se também existir um getCnpj(), ou getCpf() separados!

**Comment by Samuel-Oliveira** [comment]
E ai @phillipig Obrigado por relatar o problema. E peço desculpas pelo incoveniente em produção, tive pouco feedback sobre essa versão.
Realmente não tinha observado esse processo. 

Subi um SnapShot com a correção, consegue testar?
3.2-SNAPSHOT

Eu add alguns testes unitarios para garantir q n ocorra mais.
Caso continua o problema, peço que me sugira mais texto para eu conseguir resolver.

`
 @Test
    void extraiCpfCnpjCorretamente() {
        String textoCnpj = "C=BR, O=ICP-Brasil, OU=Secretaria da Receita Federal do Brasil - RFB, CNPJ=07364617000135";
        assertEquals("07364617000135", CertificadoService.getDocumentoFromCertificado(textoCnpj));

        String textoCpf = "C=BR, O=ICP-Brasil, OU=Secretaria da Receita Federal do Brasil - RFB, CPF=99999999999";
        assertEquals("99999999999", CertificadoService.getDocumentoFromCertificado(textoCpf));

        String textoCnpjeCPF = "C=BR, O=ICP-Brasil, OU=Secretaria da Receita Federal do Brasil - RFB, CNPJ=07364617000135, CPF=99999999999";
        assertEquals("07364617000135", CertificadoService.getDocumentoFromCertificado(textoCnpjeCPF));

        String textoCpfECNPJ = "C=BR, O=ICP-Brasil, OU=Secretaria da Receita Federal do Brasil - RFB, CPF=99999999999, CNPJ=07364617000135";
        assertEquals("07364617000135", CertificadoService.getDocumentoFromCertificado(textoCpfECNPJ));

        String textoSemNenhumDocumento = "C=BR, O=ICP-Brasil, OU=Secretaria da Receita Federal do Brasil - RFB";
        assertEquals("", CertificadoService.getDocumentoFromCertificado(textoSemNenhumDocumento));
    }
`

**Comment by phillipig** [comment]
Deu bom @Samuel-Oliveira, resolveu meu problema aqui!

Uso bastante esse método pra validar se o certificado que o cliente está enviando bate com os dados cadastrais dele / pertence a matriz, etc...

Sobre quebrar em produção, não se preocupe, faz parte do jogo, estamos ai pra fortalecer a comunidade!

**Comment by Samuel-Oliveira** [comment]
Corrigido e liberado na versao 3.2

**Comment by phillipig** [comment]
@Samuel-Oliveira, boa tarde! Eu de novo...

Trouxe um outro caso curioso que aconteceu aqui:

Tenho esse certificado:
![image](https://github.com/Samuel-Oliveira/Java_Certificado/assets/5054717/b789de83-568b-4def-b793-b09fca577495)

- Versão 2.14: .getCnpjCpf() retorna o CNPJ corretamente relacionado ao certificado.
- Versão 3.2: .getCnpjCpf()  retorna CNPJ da certificadora que emitiu o certificado (44.659.975/0001-00)

Se precisar de algo que possa te ajudar melhor, só falar!

**Comment by phillipig** [comment]
Adicional:

Quando chamo o certificate.getSubjectX500Principal().getName() para esse certificado, recebo a seguinte string (justamente de onde vem o CNPJ da certificadora):

CN=MEI COMERCIO DE ALIMENTOS LTDA,OU=Autoridade Certificadora SERPROACF,OU=ARFONSECACERT,OU=Pessoa Juridica A1,OU=44659975000100,OU=videoconferencia,O=ICP-Brasil,L=CONFINS,ST=MG,C=BR

**Comment by Samuel-Oliveira** [comment]
É @phillipig agora complicou, porque pelo que vc mostrou ai, a certificadora nao colocou o CNPJ do cliente no Subject.
Eu considero um erro dela.
Mas enfim, sugestoes? Não posso voltar o metodo antigo por falta de compatibilidade de versoes mais novas do Java.

**Comment by phillipig** [comment]
Fala @Samuel-Oliveira,

Te entendo, retornar a lib que fazia esse processo de extrair o dado correto acaba gerando outros problemas, mas por enquando estou mantendo a versão antiga da sua lib, que é o que funciona.

To tentando estudar alguma solução alternativa tbm para esse problema. Se encontrar algo, compartilho aqui.

**Comment by phillipig** [comment]
@Samuel-Oliveira bom dia

Acho que consegui chegar em uma solução que funcionou bem.

O que eu fiz: 
A informação correta que queremos está nas propriedades extendidas do certificado (OID 2.5.29.17). Até poderiamos usar alguma lib externa (o que não queremos) pra parsear esse OID, mas só de converter os bytes dessa propriedade para string, e limpar todos os caracteres não numéricos, temos uma string que dá para aplicar o regex e pegar o CNPJ / CPF do certificado.

Validei numa base de certificados que tenho acesso aqui da empresa (inclusive os que a certificadora colocou o CNPJ deles no lugar errado), e funcionou perfeitamente.

Solução proposta:

`    public String getDocumentoFromCertificado(X509Certificate x509) {
        byte[] extValue = x509.getExtensionValue("2.5.29.17");
        String extDigits = new String(extValue).replaceAll("[^\\d]+", " ");

        // Primeiro, tenta encontrar CNPJs
        Pattern patternCNPJ = Pattern.compile("(?<!\\d)\\d{14}(?!\\d)");
        Matcher matcherCNPJ = patternCNPJ.matcher(extDigits);

        if (matcherCNPJ.find()) {
            // Se encontrar um CNPJ, retorna ele
            return matcherCNPJ.group();
        } else {
            // Se não encontrar CNPJs, tenta encontrar CPFs
            Pattern patternCPF = Pattern.compile("(?<!\\d)\\d{11}(?!\\d)");
            Matcher matcherCPF = patternCPF.matcher(extDigits);

            if (matcherCPF.find()) {
                // Se encontrar um CPF, retorna ele
                return matcherCPF.group();
            }
        }

        // Se não encontrar nenhum documento, retorna string vazia
        return "";
    }`

**Comment by Samuel-Oliveira** [comment]
@phillipig Tem um topico, la no nosso discord, que chegamos a justamente nessa solucao, mas parece existir casos em que o 2.5.29.17 n retorna, te marquei la no discord no topico q estamos testando sobre isso.

**Comment by Samuel-Oliveira** [comment]
Resolvido na versao 3.3.
