### ISSUE TITLE
Caracter especial

### ISSUE THREAD

**Issue by alexnkyros** [Samuel-Oliveira/Java_Certificado#22]
Olá, tudo bem ?
Tenho um cliente que está usando o c com cedilha na senha (ç) e quando chamo o objeto CertificadoService.certificadoPfx está gerando a exceção:
out 15, 2024 5:22:08 PM com.sun.faces.context.AjaxExceptionHandlerImpl handlePartialResponseError
GRAVE: javax.faces.el.EvaluationException: br.com.swconsultoria.certificado.exception.CertificadoException: Erro Ao pegar KeyStore: Integrity check failed: java.io.IOException: getSecretKey failed: Password is not ASCII
	at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:101)
	at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:102)

Vocês teriam uma forma de impedir esse problema ?

**Comment by samuel-oliveira-tr** [comment]
Melhor forma é alterar a senha do certificado @alexnkyros 
É um procedimento muito simples que vc faz em segundos.
