### ISSUE TITLE
Falha ao inicializar SunPKCS11

### ISSUE THREAD

**Issue by egioncpdsi** [Samuel-Oliveira/Java_Certificado#3]
Olá Samuel tudo bem? Estou com problemas pra instanciar a classe SunPKCS11, está me jogando o seguinte:
Exception: java.lang.NoSuchMethodError: sun.security.pkcs11.SunPKCS11.<init>(Ljava/io/InputStream;)V
Estou utilizando Java 10 e já procurei em vários fóruns mas não encontro a solução, já se deparou com esse erro ou sabe como resolve-lo? 
Estou usando o exemplo do wiki
Desde já agradeço !

**Comment by Samuel-Oliveira** [comment]
Java 10 é um Pouco exagerado Não?
Se fosse Java 9 eu até parava para olhar...

**Comment by egioncpdsi** [comment]
Então é provavel que seria incompatibilidade? Estou começando agora nesse mundão java, vim do php então to meio perdido

**Comment by Samuel-Oliveira** [comment]
Sim, claro.
Java 10 nem foi lançado direito.
Uso o Java 8 que é a versão atyual.

**Comment by egioncpdsi** [comment]
beleza! obrigado pela ajuda !
