### ISSUE TITLE
Dúvida com uso de dois certificados.

### ISSUE THREAD

**Issue by AllisonErd** [Samuel-Oliveira/Java_Certificado#4]
Olá Samuel, boa tarde!
Primeiramente, parabéns pelo seu trabalho, acompanho muitos seus posts no Javac, e muitos problemas meus já resolvi usando dicas suas, sem fazer uso da sua biblioteca.
Pois bem, eu desenvolvi um gerenciador de Nfe, e utilizo a biblioteca do Fincatto (não sei se vc conhece), é uma biblioteca excelente, porém estou enfrentando problemas para implementar a função de funcionamento com dois ou mais certificados digitais. Quando o certificado é A1, utilizo direto pelo arquivo, quando é A3, quando existe apenas um certificado instalado na maquina (repositório do windows) funciona normalmente, quando tem mais de um instalado, ele só pega o primeiro da lista. Daí olhando sua biblioteca, vi que vc implementou essa função de selecionar o certificado, dei uma olhada, mas gostaria de uma aplicação mais aprofundada, se não fosse pedir muito, de como implementar e fazer funcionar.
Desde já agradeço a ajuda.

**Comment by Samuel-Oliveira** [comment]
Beleza? 
Conheço sim a biblioteca do Fincatto.

Aqui tem um exemplo de como usar 2 certificados A3 na mesma Maquina.
https://github.com/Samuel-Oliveira/Java_Certificado/wiki/05-:-A3-Com-varios-aparelhos-na-Maquina-Passando-o-Serial

Você deve passar o Serial do certificado para o sistema diferenciar um do Outro.

**Comment by AllisonErd** [comment]
Obrigado por responder @Samuel-Oliveira . É muito intuitiva e simples a implementação. Agora me surgiu uma dúvida, a biblioteca do Fincatto, retorna um Keystore, pra eu n ter que mexer muito, tu acha que eu conseguiria adaptar e fazer a sua biblioteca retornar um Keystore pra lá? Ou seria mais fácil alterar lá pra receber o que eu preciso? Grato.

**Comment by Samuel-Oliveira** [comment]
Já tem pronto.
O CertificadoService tem o metodo getKeyStore que vc passa como parâmetro o certificado!

**Comment by AllisonErd** [comment]
Que maravilha! 
Vou dá uma olhadinha e tentar fazer a implementação, e assim que tiver uma resposta, te dou um retorno.
Mais uma vez, muito obrigado!

**Comment by Samuel-Oliveira** [comment]
Algum FeedBAck? Posso Fechar?

**Comment by AllisonErd** [comment]
@Samuel-Oliveira não tive tempo de mexer ainda. Parei para fazer outras coisas em outros projetos. Pode fechar, quando fizer e tiver um retorno eu aviso a vc. Mais uma vez, obrigado!

**Comment by Samuel-Oliveira** [comment]
Tranquilo, Abraços!
