### ISSUE TITLE
ERRO certificate_unknown

### ISSUE THREAD

**Issue by eldevanjr** [Samuel-Oliveira/Java_Certificado#6]
Olá @Samuel-Oliveira , percebi que teve o erro  'certificate_unknown', e colocou uma correção no projeto para este erro, estou enfrentando este mesmo erro no meu projeto, gostaria de saber se tem algum detalhe que possa me passar pra eu poder corrigir, não encontrei ainda, ele faz as operações com NFe mas no CTe está dando este erro, e não acontece com todos os certificados, somente com um em específico, desde já agradecido, att.

**Comment by Samuel-Oliveira** [comment]
Blz? Recomendo usar meu projeto para testar.
Se realmente não ocorrer o erro sugiro utilizar ele.

**Comment by eldevanjr** [comment]
Fiz isso mesmo, gerei todo o XML e utilizei sua classe de parse do XML e enviei com seu projeto, e enviou, então só pode ser alguma coisa com configuração de SSL , mas não descobri o que é.

**Comment by eldevanjr** [comment]
sabe me dizer como resolveu este problema?

**Comment by Samuel-Oliveira** [comment]
- Olhe esses dois Commit:
https://github.com/Samuel-Oliveira/Java_Certificado/commit/9e57a396ff1b03a5eced20aee445fee7658d4723
https://github.com/Samuel-Oliveira/Java_Certificado/commit/8489741977c31fe1e2349bc1279af7917904c36a

**Comment by eldevanjr** [comment]
Eu estudei estes dois commits já , até fiz o clone do seu projeto, repliquei as modificações no meu projeto, mas ainda não obtive sucesso, mas agradeço pela atenção, vou tentar refatorar ou utilizar o SocketFactoryDinamico do seu projeto, pra ver se funciona, muito obrigado.

**Comment by eldevanjr** [comment]
Olá @Samuel-Oliveira , encontrei alguém com o mesmíssimo problema que o meu aqui:
https://www.javac.com.br/jc/posts/list/30/434-resolvido-problemas-com-certificado.page, ele leva pra sua página.

**Comment by eldevanjr** [comment]
Olá @Samuel-Oliveira , conseguimos utilizar o SocketFactoryDinamico que fizeste e funcionou em nosso projeto, muito obrigado!
