### ISSUE TITLE
Compatibilidade com Java 11

### ISSUE THREAD

**Issue by rodrigocananea** [Samuel-Oliveira/Java_Certificado#7]
Estou com um projeto usando Java 8 e com este pacote e está funcionando 100% gosto muito deste pacote :D, precisaria tirar uma dúvida relacionado ao Java 11 (Por culpa de outro projeto). Quando utilizado para tentar consultar o Status de Serviço do certificado ele retorna essa mensagem de erro:
java.lang.NoSuchMethodError: sun.security.pkcs11.SunPKCS11

só precisaria saber se o pacote já tem compatibilidade com o Java 11 e precisaria ser feito algo a mais ou atualmente só teria até o Java 8?

**Comment by Samuel-Oliveira** [comment]
Tudo BOm Rodrigo? 
O Projeto ja tem compatibilidade até o Java 12.

Seu erro se trata de um conflito de bibliotecas. Algum de seus imports substitui o importe da Biblioteca, o que causa o erro.

Casp queira, post seu pom aqui (ou mande por email), que eu tenho ferramentas para detectar o conflito, e adicionar os excludes necessarios.

**Comment by rodrigocananea** [comment]
Problema deste projeto que estou tendo que mexer é que não é com o Maven, está sendo utilizado o Apache Ant e no momento meu conhecimento com o Maven não está em um nível que me arriscaria a trocar para ele neste projeto hehe

**Comment by Samuel-Oliveira** [comment]
Mais facil AInda. 
Post aqui a lista de libs que vc importou manualmente e vou te dizer qual é o conflito. De cara eu digo que é a bcprov-jdk. Se vc importou ela manualmente, remova que irá funcionar.

**Comment by rodrigocananea** [comment]
https://prnt.sc/qwl02q
Não creio kkkkk, tem justamente essa que mencionou, quando eu conseguir testar ela novamente com um certificado A3 aqui dou um retorno, mas to bem otimista que vai funcionar tranquilo sem ela se notar alguma outra lib que posso obter problemas com ela futuramente me avisa dai, muito obrigado 😄
