### ISSUE TITLE
Certificado lendo bytes para várias instancias VHOST causa erro.

### ISSUE THREAD

**Issue by pedrohlira** [Samuel-Oliveira/Java_Certificado#8]
Ao utilizar o método CertificadoService.certificadoPfxBytes() em um sistema WEB que tem várias instancias de aplicações VHOST, ou seja, rodando no mesmo tomcat observei que somente o ultimo fica correto, isto por que no código abaixo da classe CertificadoProperties método inicia você cria um arquivo temporário com nome fixo, assim sendo causa o problema, diferente do método que ler o arquivo, e ele claro sendo diferente não causa o problema.

Vou submeter um PR com a correção que acredito resolver o problema, e quando atualizar o JAR mudo para usar lendo dos bytes, obrigado por manter o projeto e sempre que eu puder vou contribuir.

Abraços.

**Atual**
```
case ARQUIVO_BYTES:
                File cert = File.createTempFile("cert", ".pfx");
                Files.write(cert.toPath(),certificado.getArquivoBytes());
                System.setProperty("javax.net.ssl.keyStoreType", "PKCS12");
                System.setProperty("javax.net.ssl.keyStore", cert.getAbsolutePath());
                break;
```

**Novo**
```
case ARQUIVO_BYTES:
                String nome = UUID.randomUUID().toString();
                File cert =  #File.createTempFile(nome, ".pfx");
                Files.write(cert.toPath(),certificado.getArquivoBytes());
                System.setProperty("javax.net.ssl.keyStoreType", "PKCS12");
                System.setProperty("javax.net.ssl.keyStore", cert.getAbsolutePath());
                break;
```

**Comment by Samuel-Oliveira** [comment]
Tudo bom @pedrohlira?
Eu não passo um nome fixo, File.createTempFile você pode passar apenas um prefixo e um sufixo, o resto é gerado aleatoriamente.

O Errado no caso é usar CertificadoProperties, já que ele seta no SO o certificado, sendo assim ele vai pegar sempre o ultimo. Pra sistemas Web deixe essa propriedade desabilitada para que seja usado o Socket Dinamico.

Abraços!

**Comment by pedrohlira** [comment]
Boa noite @Samuel-Oliveira , tudo na paz. Então eu não olhei o código fonte da sua classe e não vi onde ele seta automaticamente para true e eu não faço isso em meu código. 
Quando uso passando o path do arquivo pfx funciona normal, mas quando uso passando os bytes , ai como você disse ele usa somente o último.

```
try {
            String senha = new String(Files.readAllBytes(Paths.get(Util.HDD + "/fiscal/certificado.txt")));
            String xsd = Util.REALPATH + "META-INF/xsd";
            Certificado certificado = CertificadoService.certificadoPfx(Util.HDD + "/fiscal/certificado.pfx", senha);
            ApiConfiguracao api = new ApiConfiguracao();
            CONFIG = ConfiguracoesNfe.criarConfiguracoes(EstadosEnum.valueOf(uf), AmbienteEnum.getByCodigo(api.getConfig("fis_ambiente")), certificado, xsd);
            CONFIG.setTimeout(30000);
            if (Boolean.valueOf(api.getConfig("fis_scan"))) {
                CONFIG.setContigenciaSCAN(true);
            }
        } catch (Exception ex) {
            Util.LOG.error("Erro ao inicializar configuracoes da NFe.", ex);
        }
```
se eu mudar esta linha 
**Certificado certificado = CertificadoService.certificadoPfxBytes(bytes[], senha);**
dá o problema, devo após esta linha colocar isto aqui ?
**certificado.setAtivarProperties(false);**

**Comment by Samuel-Oliveira** [comment]
Bom dia @pedrohlira , nao precisa. esse propriedade é por padrão false.
Bom, eu nuca vi este erro, precisamos de um  ambiente para testar e corrigir.
Pode montar um mini projeto que simule isso?

**Comment by pedrohlira** [comment]
Boa tarde, desculpe a demora. Vou ver se consigo criar um que simule 2 vhosts com 2 certificados diferentes para quando o tomcat subir, verificar se ele esta lendo os dois ou somente o ultimo. Ai te aviso.

**Comment by Samuel-Oliveira** [comment]
Fechado po inatividade
